### ISSUE TITLE
Last line from getHTMLBody parsed incorrectly.

### ISSUE THREAD

**Issue by franciscop** [daniele-occhipinti/php-email-parser#17]
I get some lines that shouldn't be there after the html on the body. They look like this:

```
--047d7ba984d27b4a6404f9478409--
```

There's one on each message, and they are after the `</html>` tag. I think that `getHTMLBody()` should strip that line directly. Don't you agree?

**Comment by donsander** [comment]
I found the same issue. The current code doesn't expect the trailing -- on the last boundary for the HTML section. I was able to resolve it by doing a rtrim() on the line when checking for boundary.  

 if (in_array(rtrim(substr($line, 2), "-"), $boundaries))
